### ISSUE TITLE
Rails の config を利用している部分は、別のファイルに分けたほうがよさそうです

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon_news-gatekeeper#3]
`.js.erb` にいろいろまとまっていると、のちのちメンテナンスが辛くなりそうなので js 部分と erb 部分はファイルを分けたほうがよいかなと思いました。

こんなイメージです。

* `app/assets/daimon_news-gatekeeper/config.js.erb`
  ``` js
  window.GatekeeperConfig = <%= ここで gem が持っている設定を JS のオブジェクトとして書き出す %>
  ```

* `app/assets/daimon_news-gatekeeper.js`
  ``` js
  //= require daimon_news-gatekeeper/config

  // 以下、普通の JS をごにょごにょ書きます
  ```

これはこれでグローバルに変数を生やすことになるので微妙な点ではあるのですが、わたしは仕方ないかなと考えてます… 😢 

また、gem が持っている設定値を変更したときに JS の再ビルドが必要であるということを Sprockets に伝えないと、設定変更が JS に反映されないとい>う現象が発生しそうです。

これについては、このあたりが参考になるかと思います。
https://github.com/bm-sms/mamamoi/blob/0483e9c9739ca1e7d65d3e87cbe80221a47145b3/config/initializers/assets.rb#L14-L22

**Comment by fukumame** [comment]
@tricknotes おお！　すみません、対応が漏れておりました！
対応しておきます！

**Comment by fukumame** [comment]
@tricknotes 
ご提示いただいた、サンプルコードを拝見しました！

僕の理解なのですが、こちらは`ENV['MM_DOMAIN']` が変更された時に、JSの再ビルドが走るように設定しているという認識であっていますでしょうか？
そして、`mamamoi-campaign-cookie-domain`はこの依存の設定を表すユニークキーのようなものと理解しました。

下記のstackoverflowも同じ内容を表していると理解しました。
http://stackoverflow.com/questions/35793810/how-to-add-a-rails-asset-dependency-to-an-environment-variable-with-sprockets

もし認識に誤りがあれば、ご指摘いただければ幸いです。

**Comment by fukumame** [comment]
@tricknotes 修正してみたので、お時間のある時にレビューいただけると助かります 🙇 
(gemの設定値を変更した際に、問題なくJSも更新されることも確認しました。)

**Comment by tricknotes** [comment]
今夜見てみるので少々お待ちくださいませー 🌠
